Main text update
best-practice-and-impact/CARS pull request #56
Opened 2023-07-07 13:37 UTC by shilohd

Please review main text (summary page)

2023-07-07 14:20 UTC, alexander-newton requested changes
Overall good, but need another half day I think to get this in a position to push.

The main thing is being consistent with titles ahead of charts/tables.

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +#### Open source tools have overtaken proprietary tools in capability
More analysts now feel comfortable using open source tools than proprietary tools

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +The proportion of respondents who report having the capability to use R and Python has been increasing over the past three waves of CARS. In contrast, the proportion who are able to use SAS, SPSS or
I like the additional context.

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +```{R}
would a heat map also be useful here for vis alongside the table? I'm finding it hard to fully "see" the data

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +Access to git is generally high across government. However, many have access to git but do not have the capability to use it, meaning there is more work to do to ensure analysts are able to learn the
where is the capability point coming from? If capability is also included in this figure then we should be explicit about that, but if it is not then we must say where the data on capability is coming from.

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +Please note these outputs include people who do not code at work.
"may"

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +Please note these outputs include people who do not code at work.
or be explicit about what this means for the user

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +Please note these outputs include people who do not code at work.
also don't need "please note"

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +#### Access to git
Respondents in 2022 report whether they have access to git

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +CARS::wrap_outputs("where-learned", plot, table)
can we include a title that is more explicit about what this graph is showing

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +                         xlab = "Where learned", font_size = 14,
remove xlab

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +### Most analysts' coding capabilities are actively improving
what do you mean by "actively"

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +Most respondents with prior coding experience reported that their coding capability has improved while in their current role. Again, this shows the analysis function is building capability in-house a
Most respondents with prior coding experience reported that their coding capability has improved while in their current role. This demonstrates that analysts are building capability in-house as well as being recruited with existing capability. However, results also show a minority of respondents who feel they are losing their capability. Existing skills need to be retained.

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +table <- CARS::df_to_table(tables$ability_change,
is there a rule for when tables/charts have titles and when they do not? personal preference that all tables and charts have titles or captions

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +We used cross-government data to create an ordinal regression model. How often people write code was a very strong predictor at all levels (p \< 0.001) of whether respondents report improvement to th
it's a significant predictor, but do you not agree that strength relates more to the effect size than the p-value?

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +- [RAP MVP](rap_mvp_maturity_guidance/Reproducible-Analytical-Pipelines-MVP.md%20at%20master%20·%20best-practice-and-impact/rap_mvp_maturity_guidance%20·%20GitHub)
separate list into separate paragraph for rendering. also, explain what these documents are.

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +freqs <- CARS::summarise_rap_awareness_over_time(all_wave_data)
title? also, i notice there are confidence bounds on the points - are we doing a regression here?

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +[RAP champions](https://analysisfunction.civilservice.gov.uk/support/reproducible-analytical-pipelines/reproducible-analytical-pipeline-rap-champions/) support and promote the use of RAP across gover
enquiries

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +### Respondents see the benefits of RAP but most are not currently implementing it
"most are" currently implementing it according to the paragraph that follows.

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +### Respondents see the benefits of RAP but most are not currently implementing it
most say they are implementing it but very few are implementing the RAP MVP

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +plot <- CARS::plot_grouped(tables$rap_components,
why is "functions" in the wrong order?

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +plot <- CARS::plot_grouped(tables$rap_components,
also suspect that categories "team open source code" and "use open source software" have somehow got mixed up - worth doing some QA here

2023-07-07 14:20 UTC, alexander-newton commented on quarto/main/summary.qmd
> +The findings above show that the analysis has made great strides towards RAP adoption. Using code for analysis is widespread. Open source coding tools such as R, Python, SQL and git are widely availa
analysis rather than "the analysis"

2023-07-11 15:17 UTC, shilohd commented on quarto/main/summary.qmd
> +freqs <- CARS::summarise_rap_awareness_over_time(all_wave_data)
Because some respondents repeat across waves we would be violating the assumption of independence. Unfortunately, we can't link respondents across waves, so we have no way to account for this.

2023-07-12 16:00 UTC, shilohd commented on quarto/main/summary.qmd
> +plot <- CARS::plot_grouped(tables$rap_components,
This was a bug, which is now resolved.

2023-07-13 09:12 UTC, shilohd commented on quarto/main/summary.qmd
> +The findings above show that the analysis has made great strides towards RAP adoption. Using code for analysis is widespread. Open source coding tools such as R, Python, SQL and git are widely availa
Changed to "the analysis function"

2023-07-13 19:59 UTC, shilohd commented on quarto/main/summary.qmd
> +### Respondents see the benefits of RAP but most are not currently implementing it
40% implementing, but we reported "implementing OR planning to implement", which evidently isn't very clear. I've changed it so the figure just shows the people currently implementing it.

2023-07-18 13:13 UTC, alexander-newton approved these changes

2023-07-18 15:36 UTC, merged